chains:
  - LLMChain
  - LLMMathChain
  - LLMChecker
#  - ConversationChain

agents:
  - ZeroShotAgent

prompts:
  - PromptTemplate
  - FewShotPromptTemplate

llms:
  - OpenAI
  - OpenAIChat

tools:
  - Search
  - PAL-MATH
  - Calculator
  - Serper Search

memories:
   - ConversationBufferMemory

dev: true
